apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: mysql-config
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysecret
        #       key: myrootpassword
        # #   value: R1234r
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysecret
        #       key: mypassword
        # #   value: Clarusway_1
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        resources: {}
