apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: ftmtstn/webserver13
        name: webserver13
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          value: Clarusway_1
        - name: MYSQL_USER
          value: clarus
        - name: MYSQL_DATABASE
          value: phonebook
        - name: MYSQL_DATABASE_HOST
          value: mysql
        resources: {}
